package Model;

public enum ItemTarget
{
    OWN_PLAYER,
    OWN_HERO,
    OWN_RANGED_HYBRID_HERO,
    OWN_RANDOM_FORCE,
    OWN_RANDOM_RANGED_HYBRID,
    OPPONENT_RANGED_HYBRID_HERO,
    OWN_RANDOM_MINION,
    OPPONENT_RANDOM_FORCE,
    OPPONENT_HERO,
    OPPONENT_FORCE,
    OWN_MINION,
    OWN_MELEE_FORCE,
    OPPONENT_CLOSEST_FORCE
}
