package Network;

import Model.Account;

public enum ClientCommandsEnum {
    SIGN_UP_FIND_ACCOUNT
    ,SAVE_ACCOUNT_INFO
    ,FINDACCOUNT_IN_LOG_IN
    ,LOGIN_IN_ACCOUNT_MANAGER
    ,MAIN_MENU_COMMAND
    ,MAKE_CUSTOM_SPELL
    ,MAKE_CUSTOM_MINION
    ,MAKE_CUSTOM_HERO
    ,SHOW_OUTPUT_LEADERBOARD
    ;





}
