package Network;

public enum ClientCommandEnum
{
    SIGN_UP,
    LOGIN,
    LOGOUT,
    MAKE_CUSTOM_SPELL,
    MAKE_CUSTOM_MINION,
    MAKE_CUSTOM_HERO,
    LEADER_BOARD,
    SAVE_ACCOUNT_INFO,
    BUY,
    SELL,
    IMPORT_DECK,
    EXPORT_DECK,
    CREATE_DECK,
    REMOVE_CARD_FROM_DECK,
    ADD_CARD_TO_DECK,

    MAKE_STORY_BATTLE
    ,MAKE_CUSTOM_BATTLE
    ,MAKE_MULTI_PLAYER_BATTLE
    ,GET_ALL_OF_THE_ACCOUNTS
    ,SET_BATTLEFIELD_PANES_AND_GRIDPANE
    ,SET_NEXT_CARD_PANE
    ,SHOW_BATTLE_INFO
    ,GET_FIRST_PLAYER
    ,GET_SECOND_PLAYER
    ,TASKS_WHEN_SURRENDER
    ,GET_PLAYER_TURN_GRAVE_YARD_CARDS
    ,CLEAR_HAND_PANES_IMAGEVIEW_AND_END_TURN_AND_SET_HAND_ICON
    ,SET_HEROES_FIRST_PLACE
    ,SET_HERO_ICONS
    ,SET_HAND_ICONS
    ,SET_GRID_PANE
    ;
}