package Network;

import Model.Account;

public enum CommandsEnum {
    SIGN_UP_FIND_ACCOUNT
    ,SAVE_ACCOUNT_INFO
    ,FINDACCOUNT_IN_LOG_IN
    ,LOGIN_IN_ACCOUNT_MANAGER
    ,MAIN_MENU_COMMAND
    ,MAKE_CUSTOM_SPELL
    ,MAKE_CUSTOM_MINION
    ,MAKE_CUSTOM_HERO
    ,SHOW_OUTPUT_LEADERBOARD
    ,SHOW_PROFILE_OF_ACCOUNT
    ,GET_MINIONS_OF_ACCOUNT
    ,GET_SPELL_OF_ACCOUNT
    ,GET_ITEM_OF_ACCOUNT
    ,GET_DECK_OF_ACCOUNT
    ,GET_ALL_OF_HEROES_FOR_SHOP
    ,GET_ALL_OF_MINIONS_FOR_SHOP
    ,GET_ALL_OF_SPELLS_FOR_SHOP
    ,GET_ALL_OF_ITEMS_FOR_SHOP
    ,SEND_IMPORTED_DECK_TO_ACCOUNT
    ,GET_HEROES_OF_DECK
    ,GET_MINIONS_OF_DECK
    ,GET_ITEMS_OF_DECK
    ,GET_SPELLS_OF_DECK
    ,GET_ALL_OF_THE_PLAYERS_DECK
    ,MAKE_STORY_BATTLE
    ,MAKE_CUSTOM_BATTLE
    ,MAKE_MULTI_PLAYER_BATTLE
    ,GET_ALL_OF_THE_ACCOUNTS
    ;





}
